GET http://localhost:3001/api/notes
###
GET http://localhost:3001/info
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "A new note with authentication by jwt",
    "important": true
}
###
GET http://localhost:3001/api/notes/6956b0a0a1e5c7d7d5353d18
###
DELETE http://localhost:3001/api/notes/6956b0a0a1e5c7d7d5353d18
###
PUT http://localhost:3001/api/notes/6956b0a0a1e5c7d7d5353d18
Content-Type: application/json

{
    "content": "Ensure that everything still works another time",
    "important": false
}

###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "mario",
    "name": "mario F."
}
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mario",
    "name": "mario F.",
    "password": "851d6s15"
}